export const data = { word : ["aahed","aalii","aargh","aarti","abaca","abaci",
"abacs","abaft","abaka","abamp","aband","abash","abask","abaya","abbas",
"abbed","abbes","abcee","abeam","abear","abele","abers","abets","abies",
"abler","ables","ablet","ablow","abmho","abohm","aboil","aboma","aboon",
"abord","abore","abram","abray","abrim","abrin","abris","absey","absit",
"abuna","abune","abuts","abuzz","abyes","abysm","acais","acari","accas",
"accoy","acerb","acers","aceta","achar","ached","aches","achoo","acids",
"acidy","acing","acini","ackee","acker","acmes","acmic","acned","acnes",
"acock","acold","acred","acres","acros","acted","actin","acton","acyls",
"adaws","adays","adbot","addax","added","adder","addio","addle","adeem",
"adhan","adieu","adios","adits","adman","admen","admix","adobo","adown",
"adoze","adrad","adred","adsum","aduki","adunc","adust","advew","adyta",
"adzed","adzes","aecia","aedes","aegis","aeons","aerie","aeros","aesir",
"afald","afara","afars","afear","aflaj","afore","afrit","afros","agama",
"agami","agars","agast","agave","agaze","agene","agers","agger","aggie",
"aggri","aggro","aggry","aghas","agila","agios","agism","agist","agita",
"aglee","aglet","agley","agloo","aglus","agmas","agoge","agone","agons",
"agood","agria","agrin","agros", "agued","agues","aguna","aguti","aheap",
"ahent","ahigh","ahind","ahing","ahint","ahold"]}